=== Jess-Pradeep/ccl-magento-docker/app/code/Aheadworks/Ca/etc/disallowed_company_domains.xsd
<?xml version="1.0" ?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">
    <xs:element name="config">
        <xs:complexType>
            <xs:sequence>
                <xs:element minOccurs="1" maxOccurs="unbounded" name="domains" type="domainItems" />
            </xs:sequence>
        </xs:complexType>
    </xs:element>
    <xs:complexType name="domainItems">
        <xs:sequence>
            <xs:element minOccurs="1" maxOccurs="unbounded" name="domain" type="domainItem" />
        </xs:sequence>
        <xs:attribute name="name" type="xs:string"/>
    </xs:complexType>
    <xs:complexType name="domainItem">
        <xs:attribute name="name" type="xs:string" use="required"/>
    </xs:complexType>
</xs:schema>

=== Jess-Pradeep/ccl-magento-docker/app/code/Aheadworks/Ca/etc/disallowed_company_domains.xml
<?xml version="1.0" ?>
<config xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
        xsi:noNamespaceSchemaLocation="disallowed_company_domains.xsd">
    <domains name="default-domains">
        <domain name="temp-mail.org"/>
        <domain name="emailondeck.com"/>
        <domain name="guerrillamail.com"/>
        <domain name="aol.com"/>
        <domain name="att.net"/>
        <domain name="comcast.net"/>
        <domain name="facebook.com"/>
        <domain name="gmail.com"/>
        <domain name="gmx.com"/>
        <domain name="googlemail.com"/>
        <domain name="google.com"/>
        <domain name="hotmail.com"/>
        <domain name="hotmail.co.uk"/>
        <domain name="mac.com"/>
        <domain name="me.com"/>
        <domain name="mail.com"/>
        <domain name="msn.com"/>
        <domain name="live.com"/>
        <domain name="sbcglobal.net"/>
        <domain name="verizon.net"/>
        <domain name="yahoo.com"/>
        <domain name="yahoo.co.uk"/>
    </domains>
    <domains name="global-domains">
        <domain name="email.com"/>
        <domain name="fastmail.fm"/>
        <domain name="games.com"/>
        <domain name="gmx.net"/>
        <domain name="hush.com"/>
        <domain name="hushmail.com"/>
        <domain name="icloud.com"/>
        <domain name="iname.com"/>
        <domain name="inbox.com"/>
        <domain name="lavabit.com"/>
        <domain name="love.com"/>
        <domain name="outlook.com"/>
        <domain name="pobox.com"/>
        <domain name="protonmail.ch"/>
        <domain name="protonmail.com"/>
        <domain name="tutanota.de"/>
        <domain name="tutanota.com"/>
        <domain name="tutamail.com"/>
        <domain name="tuta.io"/>
        <domain name="keemail.me"/>
        <domain name="rocketmail.com"/>
        <domain name="safe-mail.net"/>
        <domain name="wow.com"/>
        <domain name="ygm.com"/>
        <domain name="ymail.com"/>
        <domain name="zoho.com"/>
        <domain name="yandex.com"/>
    </domains>
    <domains name="usa-isp-domains">
        <domain name="bellsouth.net"/>
        <domain name="charter.net"/>
        <domain name="cox.net"/>
        <domain name="earthlink.net"/>
        <domain name="juno.com"/>
    </domains>
    <domains name="uk-isp-domains">
        <domain name="btinternet.com"/>
        <domain name="virginmedia.com"/>
        <domain name="blueyonder.co.uk"/>
        <domain name="freeserve.co.uk"/>
        <domain name="live.co.uk"/>
        <domain name="ntlworld.com"/>
        <domain name="o2.co.uk"/>
        <domain name="orange.net"/>
        <domain name="sky.com"/>
        <domain name="talktalk.co.uk"/>
        <domain name="tiscali.co.uk"/>
        <domain name="virgin.net"/>
        <domain name="wanadoo.co.uk"/>
        <domain name="bt.com"/>
    </domains>
    <domains name="asia-domains">
        <domain name="sina.com"/>
        <domain name="sina.cn"/>
        <domain name="qq.com"/>
        <domain name="naver.com"/>
        <domain name="hanmail.net"/>
        <domain name="daum.net"/>
        <domain name="nate.com"/>
        <domain name="yahoo.co.jp"/>
        <domain name="yahoo.co.kr"/>
        <domain name="yahoo.co.in"/>
        <domain name="yahoo.com.sg"/>
        <domain name="yahoo.com.ph"/>
        <domain name="163.com"/>
        <domain name="126.com"/>
        <domain name="21cn.com"/>
        <domain name="aliyun.com"/>
        <domain name="foxmail.com"/>
    </domains>
    <domains name="french-isp-domains">
        <domain name="hotmail.fr"/>
        <domain name="live.fr"/>
        <domain name="laposte.net"/>
        <domain name="yahoo.fr"/>
        <domain name="wanadoo.fr"/>
        <domain name="orange.fr"/>
        <domain name="gmx.fr"/>
        <domain name="sfr.fr"/>
        <domain name="neuf.fr"/>
        <domain name="free.fr"/>
    </domains>
    <domains name="german-isp-domains">
        <domain name="gmx.de"/>
        <domain name="hotmail.de"/>
        <domain name="live.de"/>
        <domain name="online.de"/>
        <domain name="t-online.de"/>
        <domain name="web.de"/>
        <domain name="yahoo.de"/>
    </domains>
    <domains name="italian-isp-domains">
        <domain name="libero.it"/>
        <domain name="virgilio.it"/>
        <domain name="hotmail.it"/>
        <domain name="aol.it"/>
        <domain name="tiscali.it"/>
        <domain name="alice.it"/>
        <domain name="live.it"/>
        <domain name="yahoo.it"/>
        <domain name="email.it"/>
        <domain name="tin.it"/>
        <domain name="poste.it"/>
        <domain name="teletu.it"/>
    </domains>
    <domains name="russian-isp-domains">
        <domain name="mail.ru"/>
        <domain name="rambler.ru"/>
        <domain name="yandex.ru"/>
        <domain name="ya.ru"/>
        <domain name="list.ru"/>
    </domains>
    <domains name="belgian-isp-domains">
        <domain name="hotmail.be"/>
        <domain name="live.be"/>
        <domain name="skynet.be"/>
        <domain name="voo.be"/>
        <domain name="tvcablenet.be"/>
        <domain name="telenet.be"/>
    </domains>
    <domains name="argentinian-isp-domains">
        <domain name="hotmail.com.ar"/>
        <domain name="live.com.ar"/>
        <domain name="yahoo.com.ar"/>
        <domain name="fibertel.com.ar"/>
        <domain name="speedy.com.ar"/>
        <domain name="arnet.com.ar"/>
    </domains>
    <domains name="mexico-isp-domains">
        <domain name="yahoo.com.mx"/>
        <domain name="live.com.mx"/>
        <domain name="hotmail.es"/>
        <domain name="hotmail.com.mx"/>
        <domain name="prodigy.net.mx"/>
    </domains>
    <domains name="canada-isp-domains">
        <domain name="yahoo.ca"/>
        <domain name="hotmail.ca"/>
        <domain name="bell.net"/>
        <domain name="shaw.ca"/>
        <domain name="sympatico.ca"/>
        <domain name="rogers.com"/>
    </domains>
    <domains name="brazil-isp-domains">
        <domain name="yahoo.com.br"/>
        <domain name="hotmail.com.br"/>
        <domain name="outlook.com.br"/>
        <domain name="uol.com.br"/>
        <domain name="bol.com.br"/>
        <domain name="terra.com.br"/>
        <domain name="ig.com.br"/>
        <domain name="itelefonica.com.br"/>
        <domain name="zipmail.com.br"/>
        <domain name="globo.com"/>
        <domain name="globomail.com"/>
        <domain name="oi.com.br"/>
    </domains>
</config>
